### ISSUE TITLE
Unable to get a simple repo working, after following getting started guide.

### ISSUE THREAD

**Issue by marr** [jd-solanki/anu#102]
Hi @jd-solanki -- very excited to give this library a try. I created a simple repo using vite/pnpm:

https://github.com/marr/vite-project

I'm not sure what the issue is, I think I followed the getting started instructions properly. 

https://github.com/marr/vite-project/blob/main/src/components/HelloWorld.vue#L13

When loading the dev server, there is no button rendered. The console warns:

> Failed to resolve component: ABtn

**Comment by jd-solanki** [comment]
Hi, we are improving the installation process.

Will update the docs soon. Sorry for the inconvenience.

Please update anu registration like:
```
.use(anu, { registerComponents: true })
```

Moreover, in your app due to `type="button"` styles might not get applied. Please try removing `type="button"` attr.

Waiting for your feedback 😇

**Comment by marr** [comment]
Thanks @jd-solanki -- those two things fixed the issue.
