### ISSUE TITLE
Missing Volar support for nuxt

### ISSUE THREAD

**Issue by munjalpatel** [jd-solanki/anu#103]
I see that `Volar` support for `Vue` was recently added.
Can package for `Nuxt` be patched as well with `Volar`?

This is the error I currently get in VSCode in my `nuxt` app
```
Cannot find type definition file for 'anu-vue/volar'.
  The file is in the program because:
    Entry point of type library 'anu-vue/volar' specified in compilerOptions
```

**Comment by jd-solanki** [comment]
Can you please share your tsconfig & screenshot of `anu-vue` & `@anu-vue/nuxt` in node_modules.

Awaiting your response.

**Comment by jd-solanki** [comment]
Nuxt module auto includes the types for Anu. You don't have to explicitly add them. Just make sure you are update your project to v0.12.0

Closing this as this is resolved now. Thanks for reporting :)
