### ISSUE TITLE
problem with nuxt 3 

### ISSUE THREAD

**Issue by unknownman** [jd-solanki/anu#106]
when i want to try it in nuxt 3 (stable version) the unocss.config.ts throws jiti error 

 ERROR  Cannot start nuxt:  Cannot find module 'anu-vue'                                                                                                                                    11:09:18
Require stack:
- ..../unocss.config.ts

  Require stack:
  - unocss.config.ts
  at Module._resolveFilename (node:internal/modules/cjs/loader:939:15)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at _resolve (node_modules/jiti/dist/jiti.js:1:243302)
  at jiti (node_modules/jiti/dist/jiti.js:1:245428)                                                                                                                                         11:09:16
  at unocss.config.ts:13:15
  at jiti (node_modules/jiti/dist/jiti.js:1:247502)
  at loadConfigFile (node_modules/unconfig/dist/index.mjs:145:11)
  at async Object.load (node_modules/unconfig/dist/index.mjs:74:24)
  at async loadConfig (node_modules/@unocss/config/dist/index.mjs:42:18)
  at async setup (node_modules/@unocss/nuxt/dist/index.mjs:73:35)
  at async normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:167:5)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:416:3)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:1825:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6779:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6840:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)

**Comment by jd-solanki** [comment]
Have you followed the installation instructions: https://anu-vue.netlify.app/guide/getting-started/installation.html#nuxt

**Comment by rootasjey** [comment]
I had similar issues with Nuxt 3 (`3.0.0`) and Anu `0.11.0`, but I managed to make it work with some tweaks.
I made a demo app on codesandbox here: [Nuxt 3 + Anu + UnoCSS](https://codesandbox.io/s/nuxt-3-anu-unocss-7bhoqn?file=/pages/index.vue)

Here are the necessary config files:

`package.json`:

```json
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "nuxt": "3.0.0"
  },
  "dependencies": {
    "@anu-vue/nuxt": "^0.11.0",
    "@anu-vue/preset-theme-default": "^0.11.0",
    "@unocss/nuxt": "^0.48.0",
    "@unocss/preset-icons": "^0.48.0",
    "@unocss/preset-uno": "^0.48.0",
    "nuxt-icon": "^0.1.8",
    "sass": "^1.57.1"
  }
}
```

`nuxt.config.ts` at the root of the project:

```ts
// nuxt.config.ts
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  css: [
    "@anu-vue/preset-theme-default/dist/styles.scss",
  ],
  modules: [
    "@anu-vue/nuxt", 
    "@unocss/nuxt",
    "nuxt-icon",
  ],
  unocss: {
    // presets
    uno: true, // enabled `@unocss/preset-uno`
    icons: true, // enabled `@unocss/preset-icons`
    attributify: true, // enabled `@unocss/preset-attributify`,

    // core options
    shortcuts: [],
    rules: [],
  },
})
```

Vite config file:

```ts
// vite.config.ts
import Unocss from "unocss/vite"
import { presetAttributify, presetUno } from "unocss"

export default {
  plugins: [
    Unocss({
      presets: [
        presetAttributify({ /* preset options */ }),
        // presetUno(),
        // ...custom presets
      ],
    }),
  ],
}

```

Uno config file:

```js

import { presetCore, presetIconExtraProperties } from "anu-vue"
import { presetThemeDefault } from "@anu-vue/preset-theme-default"
import {
  defineConfig,
  presetIcons,
  presetUno,
} from "unocss"

export default defineConfig({
  presets: [
    presetUno(),
    presetIcons({
      scale: 1.2,
      extraProperties: presetIconExtraProperties,
    }),

    // anu-vue preset
    // presetAnu(),
    presetCore(),

    // default theme preset
    presetThemeDefault(),
  ],
  include: [/.*\/anu-vue\.js(.*)?$/, "./**/*.vue", "./**/*.md"],
})
```

And usage in `app.vue`:

```vue
<template>
  <div flex h-full>
    <nav p-8 b-r>
      <div mb-8>Mail</div>
      <ABtn color="primary">Button</ABtn>
      <Icon name="ri:inbox-fill" size="1.5em" />
    </nav>
    <div m-16>
      <span>Hi, hello everybody! 🎄 </span>
    </div>
  </div>
</template>

```

I think that maybe a dedicated page to install Anu for Nuxt should exist, to avoid confusion.

**Comment by jd-solanki** [comment]
I suggest trying v0.12.0.

This is because v0.11.0 of `@anu-vue/nuxt` was using `anu-vue` v0.10.0. (misaligned)

In v0.12.0 both packages are aligned.

Please give it a try and let us know.

Thanks @rootasjey for sharing the configs 😇

**Comment by jd-solanki** [comment]
I'm closing this as this is resolved now. Feel free to let me know if you have any issue.
