### ISSUE TITLE
development environments has issue

### ISSUE THREAD

**Issue by jingyuexing** [jd-solanki/anu#111]
when i click components's link, then an exception is thrown.
![image](https://user-images.githubusercontent.com/19589872/210116466-6137abc1-4f66-4e5e-b352-e50f68900f61.png)

```
06:40:46 [vite] Internal server error: Missing "./component-meta/{component name}.json" export in "anu-vue" package
```

**Comment by jingyuexing** [comment]
I ran two commands.
- first
```bash
npx nr dev
```
- second
```bash
npx nr docs:dev
```

**Comment by jingyuexing** [comment]
![image](https://user-images.githubusercontent.com/19589872/210116701-e87aa8b9-6424-4fbe-8de9-8bb132e98a4b.png)
![image](https://user-images.githubusercontent.com/19589872/210116717-0d502191-a023-41cc-8871-389c888c5cf6.png)

**Comment by jd-solanki** [comment]
Hi,

Sorry when we refactored the code we removed some of the code and due to that we are now getting errors. We fixed this in the latest commit 😊 

Please give it a try and let us know.

Thanks for reporting.

**Comment by jingyuexing** [comment]
> Hi,
> 
> Sorry when we refactored the code we removed some of the code and due to that we are now getting errors. We fixed this in the latest commit 😊
> 
> Please give it a try and let us know.
> 
> Thanks for reporting.

ok now
