### ISSUE TITLE
✨ Tabs & View component

### ISSUE THREAD

**Issue by jd-solanki** [jd-solanki/anu#139]
## Quick Notes

- [x] How about adding scroll snapping when left-right arrows are clicked or x-scrolled via mouse 😍 

---

## Things to take care of

- [x] Vertical tabs
- [x] ~Allow tabs on right & bottom along with left & top.~

## Proposed API

```html
<!-- Maybe we can use provide inject so we don't have to pass v-model twice if AView is used in default slot of `ATabs` -->
<ATabs :items="['Account', 'Notifications', 'Settings']" v-model="activeTab">
  <AViews v-model="activeTab">
	  <AView value="account">Account</AView>
	  <AView value="notifications">Notifications</AView>
	  <AView value="settings">Settings</AView>
  </AViews>
</ATabs>
```

## Props

- [x] `modelValue`
- [x] `vertical`: Set tabs direction to vertical
- [x] `items`: Tabs list can also accept array of objects than can have icons
- [x] ~`fluid`: takes whole space~ `justify="stretch"` does the same
- [x] ~`justify`: start, center, end, stretch~ PR welcome

### `ATab` Props

- [x] `title`
- [x] `icon`
- [x] `appendIcon`
- [x] `disabled`

## Slots

> _We are focusing on DX here and rendering `AViews` in the default slot as this is common usage. Big reason is you don't have to create a separate state for tracking the active tab and binding it to activate the view like other frameworks 🥂_

- [x] `default`: render `AViews`
- [x] `tabs`: render tabs

## `ATab` Slots

- [x] Append & prepend slots to adding actions like close button

<details>
<summary>Phase 2</summary>

- [ ] Add support for justify prop
- [ ] Multiple design variants (requires stretchable tabs)
  - [ ] underline active
  - [ ] toggle
- [ ] What about mobile and scrolling tabs 🤔  Can we use scroll snap feature?
- [ ] Do we need active indicator UI composable?
- [ ] How about `useTabs` composable for creating tabs using buttons?
- [ ] `badge` - Configurable badge (_requires inline badge support_)

</details>

**Comment by cpreston321** [comment]
Would it be easier to write if we used slots ? 

```vue
<ATabs v-model="activeTab" :items="['Account', 'Notifications', { label: 'Settings', key: 'settings' }]">
    <template #account ></template>
    <template #notifications ></template>
    <template #settings ></template>
</ATabs>
```

This makes it more granular so it's easier to write as the ATabs is doing all the heavy lifting by determining the slots to show and hide. Also by accepting object to have a more complicated naming convention.
