### ISSUE TITLE
[ATooltip]: trigger on unexpected elements

### ISSUE THREAD

**Issue by IcetCode** [jd-solanki/anu#140]
### What is actually happening?
When we use `ATooltip` within an HTML tag, its triggering area becomes the current component instead of the current HTML tag. Here's an example:
```vue
<div class="flex flex-wrap gap-4">
  <ABtn>
    <ATooltip text="Hello!" />
    Hover Over Me
  </ABtn>

  <div>
    <ATooltip text="Hi!Anu"></ATooltip>
    Anu
  </div>
</div>
```
When the mouse moves over the entire outer div area, it triggers the appearance of the Tooltip
![image](https://user-images.githubusercontent.com/92614422/223968776-b647f03a-1ba8-4023-b2b1-b53aa0bf313a.png)

### What is Expected?
It will only be triggered by its wrapping element.

**Comment by IcetCode** [comment]
I found that this is related to the setting of parentEl, which can be seen from [here](https://github.com/jd-solanki/anu/blob/257925c19e00ca4dad5d80713021663647cfd469/packages/anu-vue/src/composables/useParentEl.ts#LL3-L7)

**Comment by jd-solanki** [comment]
Thanks for reporting. I contributed to VueUse and we can now use `useParentElement`  from VueUse but unfortunately, I'm unable to find a solid way to add a tooltip to the component.

Certainly, we can wrap the target in the tooltip for ease but let's try if we can use the correct structure and still fix the bug.

Please let me know if you have any suggestions on this.

**Comment by jd-solanki** [comment]
I checked vuetify & quasar. They are adding flag like thing to their components to correctly get the parent element.
- Vuetify adds `data-no-activator` attribute to skip the DOM element from selecting as parent and omits defining this attribute for component's root element
- Quasar uses class `q-anchor-skip` something like that to dot he same

🤷🏻‍♂️ 

We can do that but let's explore more to achieve the same this in more simpler way 😇
