### ISSUE TITLE
[useGroupModel] and [AList]: Support dynamic items

### ISSUE THREAD

**Issue by jsmnbom** [jd-solanki/anu#146]
Currently it seems that AList does not support giving it dynamic items.

In [AList](https://github.com/jd-solanki/anu/blob/4073c1c0c3846c51129cdf39efe085be837fe13d/packages/anu-vue/src/components/list/AList.vue#L29) useGroupModel gets passed options based on a mapped expression of props.items. This however makes it lose any reactivity it had. 

I've tried to fix this myself, but due to how useGroupModel works and such, it turned out to be way more complicated than i thought. I tried here: https://github.com/jd-solanki/anu/compare/main...jsmnbom:anu:gross-alist but as the branch name suggests, its really really gross (and uses a seperate useGroupModel, tho that should be easy enough to integrate back.)

Other issues I might potentially have found that should be taken into account when fixing this:
useGroupModel has no idea what the model value is. It doesn't get it passed, and if it updates, it also has no idea.
AList also doesn't seem to support bare string[] as items??

**Comment by jsmnbom** [comment]
That doesn't apply here? My issue persists even without using sets (multi=false).

**Comment by jd-solanki** [comment]
Hi, @jsmnbom @jingyuexing can you please try with the latest release?

**Comment by jsmnbom** [comment]
I tested it with commit 4073c1c0c3846c51129cdf39efe085be837fe13d originally.
You are however, completely right and this works as it is supposed to. My issue is a completely different one that i just misdiagnosed. I've submitted #151.
