### ISSUE TITLE
Changing font & color - Exploring presetWebFonts preset

### ISSUE THREAD

**Issue by jd-solanki** [jd-solanki/anu#159]
### Discussed in https://github.com/jd-solanki/anu/discussions/158

<div type='discussions-op-text'>

<sup>Originally posted by **Sandros94** April 11, 2023</sup>
I noticed that the scss from the presetThemeDefault applies the `Inter` font:
https://github.com/jd-solanki/anu/blob/d1e14de50348b0572f80d7f8ff566c411a71038c/packages/preset-theme-default/src/scss/index.scss#L9-L11
https://github.com/jd-solanki/anu/blob/d1e14de50348b0572f80d7f8ff566c411a71038c/packages/preset-theme-default/src/scss/index.scss#L89-L107

Can I change it from `uno.config.ts` or should I just overwrite the body and heading styles?</div>

**Comment by Sandros94** [comment]
If I can help you just ping me.
I'm not that great with js/ts yet, but I'm learning and I'm starting to get a decent knowledge of Nuxt 3

**Comment by jd-solanki** [comment]
oh, So nice of you 🙏🏻 

Sure, I will let you know 😇

**Comment by jd-solanki** [comment]
Hey @Sandros94 

Thanks for your patience and reporting the issue. Anu now no longer handles the font-family customization, Instead we now allow using `presetWebFonts` for fetching & changing the font-family.

From the next release (now on, if you are using edge releases) you will be able to customize the fonts via [web fonts](https://unocss.dev/presets/web-fonts) UnoCSS preset.

For color, We now have CSS variable for each theme so that can you can have different color for each theme: https://github.com/jd-solanki/anu/blob/main/packages/anu-vue/src/plugin.ts#L39

Please let me know your thoughts on this.

**Comment by Sandros94** [comment]
I'll checkout the edge release as soon as I get back home/office. The changes look perfect already ♥️

**Comment by jd-solanki** [comment]
Hi, I have made a new release. Can you please give it a try?

**Comment by jd-solanki** [comment]
> _I still need to specify in the vue style to apply the unocss font-sans_
You mean you still have to write `font-family: 'xxx'`, right? If yes, That happened to me as well. Maybe we have to first test if this is from UnoCSS or not.

> how to customize my presetAnu
I'm willing to add docs for this. If you have something to ask regarding this, let's discuss this in discord thread.

> _I get a warning_
🤔  Strange, I'll look into this

**Comment by Sandros94** [comment]
> You mean you still have to write `font-family: 'xxx'`, right? Maybe we have to first test if this is from UnoCSS or not.

Yes, and indeed this is the case: on a fresh unocss install (without anu) I have to specify the font-family (even for sans).

> I'm willing to add docs for this. If you have something to ask regarding this, let's discuss this in discord thread.

Sounds good, later I'll open the discussion there.

**Comment by jd-solanki** [comment]
> I have to specify the font-family

Can you please raise issue on uno repo and reference here for tracking?

**Comment by Sandros94** [comment]
> Can you please raise issue on uno repo and reference here for tracking?

it has been a busy day, doing it now.

**Comment by jd-solanki** [comment]
Hi @Sandros94 Apart from mentioned issue. I think everything is resolved now from Anu's side, Am I right?

**Comment by Sandros94** [comment]
@jd-solanki following [the reply](https://github.com/unocss/unocss/issues/2659#issuecomment-1582622025) we got there I would close this issue as fully completed now.

**Comment by jd-solanki** [comment]
@Sandros94 Yes, Let's close this.
