### ISSUE TITLE
DOCS: document style mistake

### ISSUE THREAD

**Issue by jingyuexing** [jd-solanki/anu#163]
![image](https://user-images.githubusercontent.com/19589872/232403602-027538b2-f7ff-44bc-94f9-610092fdcd4e.png)

**Comment by jd-solanki** [comment]
Hi @jingyuexing Thanks for reporting. I was trying to fix it but it looks like it's no longer the case.

Can you please recheck?

**Comment by jingyuexing** [comment]
> Hi @jingyuexing Thanks for reporting. I was trying to fix it but it looks like it's no longer the case.
> 
> Can you please recheck?
![image](https://user-images.githubusercontent.com/19589872/232746323-daebf8e4-46e6-40cf-85b7-383627426296.png)
![image](https://user-images.githubusercontent.com/19589872/232746292-97e8315b-8567-427a-b41b-d2d3bd93db60.png)

PS:I guess maybe just need to adjust the z-index property in css

**Comment by jd-solanki** [comment]
Yes, I know that is `z-index` issue but I'm not getting the issue now. Can you please check it and let me know.

Awaiting your response.

**Comment by jd-solanki** [comment]
oh, Sorry I was checking in dark mode 🙏🏻 

Let me fix it.

**Comment by jd-solanki** [comment]
FYI, We will be improving z-index in upcoming release that will completely remove z-index related issues. Thanks for reporting.

**Comment by jingyuexing** [comment]
> 

This is because the z-index setting of the syntax highlighting content is relatively large. Most of the content in the code block can float on top of other elements.
