### ISSUE TITLE
Customize Button component's flex direction

### ISSUE THREAD

**Issue by larrasu** [jd-solanki/anu#169]
It doesn't override when I apply `justify-start` class on the component:
```vue
<ABtn :icon="item.icon" variant="text" class="w-full justify-start" >{{ item.title }}</ABtn>
```

![image](https://user-images.githubusercontent.com/74983120/236218532-c05391de-1e86-4e77-aad2-12f6c6f23f75.png)

I was hoping to add a prop for this.

**Comment by jd-solanki** [comment]
Button is justified to center via `justify-center`, use `!justify-start` to override that.

```vue
<template>
  <div>
    <ABtn class="w-full !justify-start">
      Primary
    </ABtn>
  </div>
</template>

```
