### ISSUE TITLE
Crashes unocss on fresh vitesse project "unknown word"

### ISSUE THREAD

**Issue by lmeysel** [jd-solanki/anu#18]
Setting up a brand new vitesse project, anu will make the build to fail saying "Unknown Word".

Steps to reproduce:
* Create new [vitesse project](https://github.com/antfu/vitesse#clone-to-local)
* Install anu according to the [docs with auto-import](https://anu-vue.netlify.app/guide/getting-started/installation.html#auto-importing-components-w-tree-shaking) (side-note: besides the installation instructions for auto-import, I updated the unocss.config.ts [as written before (in Usage, step 2)](https://anu-vue.netlify.app/guide/getting-started/installation.html#usage)
* Add the following to `pages/index.vue`:
```vue
<ACard variant="outline" title="MyCard" subtitle="This is the subtitle" />
```
* run `pnpm dev`

The page now shows the following error:
![image](https://user-images.githubusercontent.com/12410218/191500207-aa1f5eb2-d276-4646-87ad-001010f612d1.png)

**Comment by jd-solanki** [comment]
Thanks for raising the issue, are you able to run the vitesse project without anu using UnoCSS?

**Comment by lmeysel** [comment]
Yup, is working. Using unocss inspector i found the issue seems to come from a wrong escaping in the stylesheet, generating the following line:
```css
${t}.a-layer-active::before{opacity:var(--\{a\});}
```

**Comment by jd-solanki** [comment]
Thanks! I will check that out 😇

**Comment by lmeysel** [comment]
It seems not to be a problem in master, as the corresponding lines were removed in [this commit](https://github.com/jd-solanki/anu/commit/5f48499c069eeff7f77210f53517bed81fc81ea6). Thus I only find the rules in the bundle but not in the repository anymore.

**Comment by lmeysel** [comment]
Okay, confirmed. Using anu from master works fine! (Conflicts with vue reactivity transform then, but that is probably part of another story)

**Comment by jd-solanki** [comment]
How did you tested from master branch?

**Comment by lmeysel** [comment]
Cloned the repo, `pnpm buld` it and then `pnpm add ../anu/packages/anu-vue` in my Vitesse Project (considering the anu repo directory resides next top the vitesse's one)

**Comment by jd-solanki** [comment]
If this is fixed in the latest commit, can we close this?

**Comment by lmeysel** [comment]
I think so
