### ISSUE TITLE
Have a Bug in the switch component?

### ISSUE THREAD

**Issue by QC2168** [jd-solanki/anu#220]
I using switch components, But when I click on this switch component TAB, the switch changes

this is feature or bug?

Demo: https://anu-vue.netlify.app/guide/components/switch.html

**Comment by jd-solanki** [comment]
Sorry I didn't get what you mean, Can you please explain a bit more and provide GIF or video if possible.

**Comment by QC2168** [comment]
![image](https://github.com/jd-solanki/anu/assets/82024018/0291ef40-950b-472b-83d5-b0dc3278543a)

**Comment by QC2168** [comment]
I understand, this is a normal situation
