### ISSUE TITLE
List component unusable with TypeScript

### ISSUE THREAD

**Issue by SoCuul** [jd-solanki/anu#228]
I'm trying to use the list component with an object for the items param, but TypeScript keeps warning me that this is not possible.
<img width="733" alt="image" src="https://github.com/jd-solanki/anu/assets/63339559/d79da942-3084-409e-9efa-6b9320e22610">

**Comment by SoCuul** [comment]
@jd-solanki

**Comment by jd-solanki** [comment]
@SoCuul Sorry for the delay. Unfortuently, I don't get enough time to maintain this lib.

If you like to handle this I would love to add you as a member.

Also, We now have much better libs in Vue ecosystem like RadixVue + ShadcnVue & Nuxt UI if you like to try.

**Comment by SoCuul** [comment]
@jd-solanki Thank you so much for the response. Do you have any suggestions for component libraries with similar design elements as Anu?

My favourite thing about this library is how amazing the elements look out of the box.

**Comment by jd-solanki** [comment]
I prefer [radix-vue](https://radix-vue.com/) & [shadcn-vue](https://www.shadcn-vue.com/) these days.

I would love to work on it but in the end it all comes down to time it takes to maintain it.

Thanks for your inputs & contribution and sorry for not being able to keep it up 🙏🏻
