### ISSUE TITLE
dev mode with pnpm

### ISSUE THREAD

**Issue by ManUtopiK** [jd-solanki/anu#23]
I was dreaming of a UI framework with vueUse and unoCSS and you have done. Awesome! Thanks.

I followed the file [contributing](https://github.com/jd-solanki/anu/blob/main/CONTRIBUTING.md) to install in my computer and fix some issue.
But it was a little bit painful. I had to do `ni (pnpm i)` everywhere. In the root folder, in `packages/anu-vue` and `packages/documentation`.
Also, from the root folder, `nr dev` and `nr dev:docs` don't work. I had to start two terminal instances not from the root folder but from both `packages` to prevent vite and vitepress errors.

I wonder how is your dev workflow?

**Comment by jd-solanki** [comment]
> I was dreaming of a UI framework with vueUse and unoCSS and you have done. Awesome! Thanks.

I am glad we are building the framework together everyone wanted ❤️ 

Here's TL;DR

1. Clone the forked repo
2. Run `ni` (It installs all the dependencies required)
3. Open new terminal in vscode and run `nr dev` (It will start the anu in dev mode)
4. Open new terminal in vscode and run `nr docs:dev` (It will start the docs in dev mode)
5. Open the shown URL after running docs command and we are done 🥳 

The rest of the things are mentioned in contributing, Please let me know if you have any further queries.

BTW, how did you find Anu? 🤔

**Comment by ManUtopiK** [comment]
Thanks for your response.

Below, I relate my installation experience :
At step 2, running `ni` at the root folder doesn't install all dependencies for me.
After running `ni`, the command `nr dev` return `vite: command not found`. Therefore, I installed `vite` globally, but I get another error `Cannot find package '@vitejs/plugin-vue'`...

So, I run the command `ni` directly in each `packages`, but in `packages/documentation`, `ni` fail with `Unsupported URL Type "workspace:": workspace:*`. But `pnpm i` didn't fail !

After struggled with this installation, I can run `nr dev` and `nr docs:dev` from the root folder.

I found Anu from the [unocss readme](https://github.com/unocss/unocss#community-frameworks) :rocket:

**Comment by jd-solanki** [comment]
That's strange 🙄 

Anyways, as we are using `pnpm` you can use `pnpm` commands directly instead of `ni`.

However, if possible please try cloning the repo again (_just for checking_) and follow the steps as mentioned above, IG there might be some glitch.

If you already have `pnpm` installed make sure it's not too old.

> I found Anu from the [unocss readme](https://github.com/unocss/unocss#community-frameworks) 🚀

Great!

If still find this installation issue after a fresh clone please let me know.

Happy coding 🙌🏻

**Comment by jd-solanki** [comment]
@ManUtopiK If this issue is resolved can we close this?

**Comment by ManUtopiK** [comment]
I tried again and I confirm that I can get everything installed with `pnpm i` but not with `ni` from the root folder.
You can close this issue at anytime.

**Comment by jd-solanki** [comment]
Do you need to run pnpm i in every dir or just in root?

**Comment by ManUtopiK** [comment]
Just in root.

**Comment by jd-solanki** [comment]
And with `ni` this doesn't work. You have to go to each dir, right?

**Comment by ManUtopiK** [comment]
Exactly!

**Comment by ManUtopiK** [comment]
Since I updated `pnpm` and did a `corepack enable` command, everything works as expected!
I close this issue.
Thanks.
