### ISSUE TITLE
docs not work.

### ISSUE THREAD

**Issue by abumalekFayed** [jd-solanki/anu#28]
Documentation link not work.

**Comment by jd-solanki** [comment]
Can you please share the link?

**Comment by abumalekFayed** [comment]
https://anu-vue.netlify.app/guide/getting-started/installation.html

**Comment by abumalekFayed** [comment]
The link is worked now 
Thank you for this awesome project.

**Comment by jd-solanki** [comment]
Thanks 😇

**Comment by jd-solanki** [comment]
BTW @abumalekFayed How did you find Anu?
