### ISSUE TITLE
feat: Add `Nuxt` Module

### ISSUE THREAD

**Issue by cpreston321** [jd-solanki/anu#31]
# Context 

Create a `nuxt module` so we can easily use it with our `Nuxt 3` projects. It will make it easier to setup since `Nuxt` makes it super powerful to auto import and compassables with `@nuxt/kit`. 

## Examples 

https://github.com/unocss/unocss/tree/main/packages/nuxt

Thanks 💚

**Comment by jd-solanki** [comment]
Closed via #81

This will be available in the next release.
