### ISSUE TITLE
ASelect example with slots are not working

### ISSUE THREAD

**Issue by peterbud** [jd-solanki/anu#38]
At the [examples page](https://anu-vue.netlify.app/guide/components/select.html) the **Slot** example is not working. The dropdown appearing nicely, but whatever the user selects it is not appearing in the input box:

![slot](https://user-images.githubusercontent.com/7863452/194754916-46f8efed-b84b-4aaa-9cb2-17025b6a5d95.gif)

**Comment by brojor** [comment]
Thank you for finding this issue @peterbud. This appeared after commit [2d1ff81](https://github.com/jd-solanki/anu/commit/2d1ff81ba47e21d3514216cbbc168837de455bc7). 
I'll go fix it right now.

**Comment by jd-solanki** [comment]
Can confirm it is fixed.

CI deploys are stopped right now for v0.10.0 so no one will be able to see the fixed docs but give me a couple of days it will be back.

Thanks, closing this 😇

**Comment by peterbud** [comment]
Thanks guys for the fix, much appreciated
