### ISSUE TITLE
pagination in table component does not work well

### ISSUE THREAD

**Issue by knoxnoe** [jd-solanki/anu#46]
https://user-images.githubusercontent.com/73536160/195962495-86472679-e17d-4dd0-80e1-45b74c9ad7b8.mov

v-slots closure causes the view layer to be unbound?

**Comment by jd-solanki** [comment]
There's no code to look at? Also mention what is expected behavior and what is happening.

Can you please recreate this in sandbox via [this](https://codesandbox.io/s/anu-demo-psqxec) link?

Thanks.

**Comment by knoxnoe** [comment]
sorry, reply so late!

where: 
last table demo in offical doc
https://anu-vue.netlify.app/guide/components/table.html

**Comment by jd-solanki** [comment]
Hi @knoxnoe 

Is it fixed now? It is resolved on its own. Maybe it was some deployment issue.

Can we close this if this is resolved?
