### ISSUE TITLE
New component: Chip

### ISSUE THREAD

**Issue by Mashiane** [jd-solanki/anu#5]
Wow, this is awesome and beautiful. Love it.

Q1. Not sure, can you please add functionality how to create nice chip & chip groups?

Q2. Is there a CDN version of this to use via the <script> tag?

Thank you so much!

**Comment by jd-solanki** [comment]
Chip groups? Can please share the UI of chip groups? Or do you mean a group of chips just like [this](https://anu-vue.netlify.app/guide/components/checkbox.html#array) checkbox demo

**Comment by Mashiane** [comment]
Yep...

![image](https://user-images.githubusercontent.com/5799306/189382710-8b65fe56-f6bc-457f-811e-88b1f9881bf8.png)

Source: https://vuetifyjs.com/en/components/chips

Thanks

**Comment by jd-solanki** [comment]
I have chips in my pipeline but first I have to complete list & menu component.

Thanks for your interest.

**Comment by jd-solanki** [comment]
Closed via #56
