### ISSUE TITLE
v0.11.0

### ISSUE THREAD

**Issue by jd-solanki** [jd-solanki/anu#50]
Hi 👋🏻

## Plans

- [x] Improving flexibility of sizing the component (_experiment_)
  - currently, if we reduce the size of the component via font size utility it also reduces the font size of the component along with its spacing. With the new ~~`--a-spacer`~~ `--a-spacing` CSS var we will try to provide more flexibility on sizing ~~and let font size utility only change the font size~~. This is helpful in cases where we might need a smaller size of the component but we need font size to be as it is.
- [x] ~Creating a new composable `usePopper` to handle popups & dialogs. This will be used in the select, menu and if possible we will try to implement it in Drawer & dialog as well.~
- [x] We will move docs dir outside of `packages` dir
- [x] Better handling of font size in the card & outside of the card. It's hard to decide what should be the font size of the card text. At the moment card internally modifies the card text and sets its font size to 14px but it increases the complexity a bit and the default font size in the browser is 16px. So, first we have to decide:
  - What should be the default font size?
  - If it's 16px don't do anything and it will remove complexity in typography & card component
  - It it's 14px we need to find better way after we implement `--a-spacer` to handle font size easily considering DX. I prefer not to write `a-card-text` everytime I need card text, to be honest.
- [x] We need to provide a way to render only icon (not avatar) to list. At the moment we can use `icon` prop but it is consumed by `avatar` component. Hence, we have to render icon via the `avatar` component which requires a few adjustments to sizing. We will try to differentiate avatar component's prop via new prop `$avatar` or something else to separate general props & internal component props. This will ease development and will be clear if we provide passing props for multiple internal components in a single parent component.
- [x] Base input allow arbitrary content in append & prepend slot - remove absolute positioning for icons.

## Additionally

- [x] create separate package for preset theme default _(requires installation update)_
- [x] Providing NuxtJS Support
- [x] Fix Reported bugs
  - [x] if we click on switch twice it selects text
  - [x] typography comp renders header even if we just use text
  - [x] dialog & select etc SSR issue
- [x] ~Improve installation process (_reducing steps required to get started_)~
- [x] ~`ARow` & `ACol` + `ACol` & `repeat` prop (_repeat prop will improve the DX 😍_)~ Will render all slots if we change any of slot reactivity
- [x] ~Branding (logo & landing page)~ Later
- [x] ~base roundness~
- [x] ~icon aliases~ as per feat req
- [x] add linting rules
  - [x] https://github.com/vuejs/eslint-plugin-vue/issues/1993
- [x] ~rename transition => slide up & bottom~ _(invalid)_

> _P.S. Soon I will make a project for our upcoming updates and interations_

**Comment by productdevbook** [comment]
iam send two pr 

nuxt 3 -> https://github.com/jd-solanki/anu/pull/81
volar support -> https://github.com/jd-solanki/anu/pull/82

**Comment by jd-solanki** [comment]
Closed via https://github.com/jd-solanki/anu/commit/0c57c00698bfb301a7af4cd461e8600550ce6258
