### ISSUE TITLE
ADialog: Using classes causes warning and is ignored

### ISSUE THREAD

**Issue by lmeysel** [jd-solanki/anu#59]
When using `ADialog` and passing a class to it (e.g. `w-800px`) the following warning shows in the console. The class seems not to be applied.

![image](https://user-images.githubusercontent.com/12410218/198548350-e08c10f0-00a6-4f20-874a-0546d97112a0.png)

**Comment by jd-solanki** [comment]
Will check it out soon 😇

**Comment by brojor** [comment]
Since we don't need to inherit classes for the root element of `<Adialog>`, I suggest disabling argument inheritance. Classes are transferred to the nested `<ACard>` via `{ ...attrs }`.
