### ISSUE TITLE
Feature: Add ToolTip Component

### ISSUE THREAD

**Issue by sfxcode** [jd-solanki/anu#65]
Hi,

i use your library in our internal company blog (VitePress, UnoCSS, Anu) and a tooltip component would be really helpful for our custom components inside this blog.

Because there are not to many good examples on VitePress for easy blogging i made a starter project built on my learnings so far and included  Anu as component framework [vitepress-blog-starter](https://github.com/sfxcode/vitepress-blog-starter). 

@jd-solanki Really like your work! Great Job!

Thanks and a great coding time,
Tom

**Comment by jd-solanki** [comment]
## Features / Things to take care of

- [ ] Support show/hide delay. Type: `number | { show: number, hide: number }` (use VueUse function)
- [ ] What about offset 🤔 
- [ ] Allow changing transition

## Proposed API

## Props

- [ ] _`AFloating` props_
- [ ] `text`: render text in tooltip

## Slots

- [ ] Default - render custom content inside tooltip

## Events

- [ ] show
- [ ] hide

<details>
<summary>Next phase</summary>

- [ ] Add arrow support

</details>
