### ISSUE TITLE
Bug: AList error when default slot is used without providing items prop

### ISSUE THREAD

**Issue by soulsam480** [jd-solanki/anu#66]
To reproduce:
- component
```vue
<script lang="ts" setup>
const items = [
  { title: 'Donut jujubes' },
  { title: 'Sesame snaps' },
  { title: 'I love jelly' },
  { title: 'Cake gummi', disable: true },
]
</script>

<template>
  <div class="cards-demo-container">
    <ACard>
    <AList>
      <li v-for="item in items" :key="item.title">
        {{ item.title }}
      </li>
    </AList>
    </ACard>
  </div>
</template>
```
- error
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'value')
    at setup (anu-vue.js:1094:27)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7204:29)
    at setupComponent (runtime-core.esm-bundler.js:7159:11)
    at mountComponent (runtime-core.esm-bundler.js:5508:13)
    at processComponent (runtime-core.esm-bundler.js:5483:17)
    at patch (runtime-core.esm-bundler.js:5085:21)
    at mountChildren (runtime-core.esm-bundler.js:5269:13)
    at mountElement (runtime-core.esm-bundler.js:5179:13)
    at processElement (runtime-core.esm-bundler.js:5162:13)
```

**Comment by soulsam480** [comment]
I suspect the error is coming from here https://github.com/jd-solanki/anu/blob/c0026f8b7d8a383ccb8d6e91ffb672100972d92e/packages/anu-vue/src/components/list/AList.tsx#L76 . Please tell me how can I help.

**Comment by jd-solanki** [comment]
Maybe we have to do:

```diff
- props.items[0].value ? props.items.map(i => i.value) : props.items.length
+ props.items && props.items[0].value ? props.items.map(i => i.value) : props.items.length
```

However, we might have to take care of other things like click: https://github.com/jd-solanki/anu/blob/c0026f8b7d8a383ccb8d6e91ffb672100972d92e/packages/anu-vue/src/components/list/AList.tsx#L102

**Comment by jd-solanki** [comment]
@soulsam480 I'm on it

**Comment by jd-solanki** [comment]
Maybe I should learn how to write tests now

**Comment by jd-solanki** [comment]
Hi @soulsam480 

Why do you need default slot?

You might be looking for item slot to render the custom content inside the list item, right?

**Comment by jd-solanki** [comment]
Closed via https://github.com/jd-solanki/anu/commit/467f8df3d0860c5dc27f5d2d8f7e5daafe92485a

**Comment by soulsam480** [comment]
> Hi @soulsam480
> 
> Why do you need default slot?
> 
> You might be looking for item slot to render the custom content inside the list item, right?

Yessir correct. Also the current API design is great, but in terms of flexibility, I think we can do better. e.g. in a list along with `prepend` and `append` slots, an item prop be super flexible. I think you already know this, but taking some inspiration from the API design of `Quasar` will be a great idea as it's the holy grail of vue component lib IMO. anyways awesome work, if your gihub sponsors is open, would love to contribute some.

**Comment by soulsam480** [comment]
> Maybe we have to do:
> 
> ```diff
> - props.items[0].value ? props.items.map(i => i.value) : props.items.length
> + props.items && props.items[0].value ? props.items.map(i => i.value) : props.items.length
> ```
> 
> However, we might have to take care of other things like click:
> 
> https://github.com/jd-solanki/anu/blob/c0026f8b7d8a383ccb8d6e91ffb672100972d92e/packages/anu-vue/src/components/list/AList.tsx#L102

I think this will still fail, if the items array is empty, i.e. first item is undefined and the error will be can't read property value of undefined. fix can be making it an optional chain e.g. 
```ts
 props.items && props.items[0]?.value ? props.items.map(i => i.value) : props.items.length
```

**Comment by jd-solanki** [comment]
Hi @soulsam480 

> item prop be super flexible
prop or slot?

> if your gihub sponsors is open, would love to contribute some
Thanks for the honor. I will open sponsorship later but first I want to provide some value via this framework.

Regarding the last [reply](https://github.com/jd-solanki/anu/issues/66#issuecomment-1304792351), I pushed new commit that:
- Allows `item` slot so that you can customize the list item rendering. `item` slot provides `item` & `index` as slot props.

Source [code](https://github.com/jd-solanki/anu/blob/main/packages/anu-vue/src/components/list/AList.tsx#L156-L159)

I hope this will resolve this issue. Have you checked the anu with latest update (_I haven't released the change yet but you can try master branch_)

Awaiting your response.

**Comment by soulsam480** [comment]
> I hope this will resolve this issue. Have you checked the anu with latest update (I haven't released the change yet but you can try master branch)

> Awaiting your response.
Just checked, super work. I think this solves my thing. thx for your work again.
