### ISSUE TITLE
ATable does not change on rows Prop change

### ISSUE THREAD

**Issue by peterbud** [jd-solanki/anu#67]
When I set the rows Prop of the ATable to a reactive Array it displays the content as expected. If I change the reactive Array (like adding a new element) ATable does not refresh its content. If I change the pagination the new row becomes visible.

![error](https://user-images.githubusercontent.com/7863452/200830263-1f2fae4f-ec6c-48e3-be81-f177333a0a9a.gif)

Here the relavant code:

```vue
<script setup lang="ts">
const fakeDatabase: User[] = [
  {
    id: 1,
    name: 'Leanne Graham',
    username: 'Bret',
    email: 'Sincere@april
...
}]
const dbRef = ref<User[]>(fakeDatabase)

function addRow() {
  dbRef.value.push({
    id: 100,
    name: 'New User',
    username: 'newuser',
    email: 'newuser@whatever.com',
 ...
 })
}
</script>

<template>
  <div class="cards-demo-container">
    <ABtn @click="addRow">Add New Item</ABtn>
    <ATable :rows="dbRef" :columns="cols" :page-size="15" />
  </div>
</template>
```
Looking at the code `recalculateCurrentPageData` is only called when the search or the sorting is changed, but not when the rows are changing.

In general, the question is what the designated way is to update the content of the ATable?

**Comment by jd-solanki** [comment]
Hi @peterbud,

Can you confirm if this is resolved or not with the latest change?

**Comment by peterbud** [comment]
Should I wait for a next release or you meant to build and test it myself in my project?

**Comment by jd-solanki** [comment]
Try this: https://github.com/jd-solanki/anu/issues/18#issuecomment-1254548915

**Comment by peterbud** [comment]
The new change results and error in build:
```
src/components/table/ATable.tsx:242:21 - error TS2540: Cannot assign to 'value' because it is a read-only property.

242       paginatedRows.value = sortedRows.value.slice(start, end)
```

**Comment by peterbud** [comment]
No worries, I have just checked, the latest change indeed fixed the issue, many thanks!

**Comment by jd-solanki** [comment]
That's awesome 🥂

**Comment by nanotronic** [comment]
It seems that the bug is back in 0.12.0 when I use data table.
