### ISSUE TITLE
ATable: Pagination calculation error

### ISSUE THREAD

**Issue by peterbud** [jd-solanki/anu#70]
ATable pagination footer shows for the actual page info in a [FROM] - [TO] of [TOTAL] format.
However, the [TO] is always a static number, depending on the page size. You can check in the [docs example](https://anu-vue.netlify.app/guide/components/table.html) if you try to move to the second page, it shows "6-5 of 10"m insetad of the correct "6-10 of 10":

![error](https://user-images.githubusercontent.com/7863452/201415961-bb009366-2662-4ad0-b184-aba1d8047de4.gif)

**Comment by jd-solanki** [comment]
I have to learn vitest now 😂

**Comment by peterbud** [comment]
:) I have some expereince with vitest, I would be happy to help to set up the framework for component testing

**Comment by jd-solanki** [comment]
Once we release v0.11.0 we will implement vitest.

Thanks for the support 😇

**Comment by peterbud** [comment]
FIrst draft: https://github.com/peterbud/anu/commits/vitest
