### ISSUE TITLE
(fix): AChip component is not being exported

### ISSUE THREAD

**Issue by therealokoro** [jd-solanki/anu#73]
So i tried importing AChip, but it's not part of the exports which is weird because i have gone through your code and i can see it exported

![image](https://user-images.githubusercontent.com/41494675/201711976-2b1d95a1-4845-443a-9921-8279a896d564.png)

**Comment by jd-solanki** [comment]
Chip component isn't released yet. It will be available in v0.11.0

For now if you want to try latest changes, please refer to [this](https://github.com/jd-solanki/anu/issues/18#issuecomment-1254548915)  comment

It will be released with rating component and nuxtjs support

**Comment by therealokoro** [comment]
@jd-solanki alright...thanks

**Comment by jd-solanki** [comment]
@therealokoro  Can we close this?

**Comment by therealokoro** [comment]
very well @jd-solanki 

I guess i'll just have to wait till the next release 🙂
