### ISSUE TITLE
Where does the AListItem in the document come from?

### ISSUE THREAD

**Issue by jingyuexing** [jd-solanki/anu#83]
- [document](https://anu-vue.netlify.app/guide/components/list.html)
Is it a custom component?

**Comment by jingyuexing** [comment]
i know now ，i need upgrade pack

**Comment by jd-solanki** [comment]
It's new component but isn't released yet.

Maybe i will make new release tomorrow.

Stay tuned 😇

**Comment by jd-solanki** [comment]
It's live now 😍 

Installation have breaking changes: https://github.com/jd-solanki/anu/blob/main/docs/guide/getting-started/installation.md
