### ISSUE TITLE
[unocss]: variant group classes in `ARadio` but there isn't `transformerVariantGroup` in uno.config.ts

### ISSUE THREAD

**Issue by ManUtopiK** [jd-solanki/anu#92]
`ARadio` component use [variant group classes](https://github.com/jd-solanki/anu/blob/main/packages/anu-vue/src/components/radio/ARadio.tsx#L60), but `transformerVariantGroup` isn't explicitly imported in [install doc](https://anu-vue.netlify.app/guide/getting-started/installation.html#usage)

I don't find any other variant group classes except in [the doc](https://github.com/jd-solanki/anu/blob/fcacbab98e16ce9c7c131265632eff590dadaa0f/docs/index.md?plain=1#L24) (but the [uno.config.ts for the doc use `transformerVariantGroup`](https://github.com/jd-solanki/anu/blob/fcacbab98e16ce9c7c131265632eff590dadaa0f/docs/uno.config.ts#L32)).

Should we replace classes in `ARadio` or add `transformerVariantGroup` in default config ?

**Comment by jd-solanki** [comment]
I think you are right. Maybe radio isn't getting that style, right?

Can you please share a screenshot of your app for confirmation?

We should provide the generated CSS instead of forcing users to install various transformers.

We look into this for next release 👍🏻 

Thanks for reporting

**Comment by ManUtopiK** [comment]
> I think you are right. Maybe radio isn't getting that style, right?

Yes, that's it !

My code :
```vue
<div class="flex gap-x-6">
  <ARadio
    v-model="userLocale"
    name="language"
    value="en"
    label="En"
  />
  <ARadio
    v-model="userLocale"
    name="language"
    value="fr"
    label="Fr"
  />
</div>
```
Result :
![image](https://user-images.githubusercontent.com/188172/205891100-558ad6fd-fc4d-43d8-8c4e-63fb03ec262a.png)

> We look into this for next release 👍🏻

Awesome !

**Comment by jd-solanki** [comment]
Closed via https://github.com/jd-solanki/anu/commit/b1f8d721d5d46446666d5e93fb42876e2818ee66
