### ISSUE TITLE
The module `"anu-vue/dist/types"` "has no exported member `"presetCore"` .

### ISSUE THREAD

**Issue by evanlong0926** [jd-solanki/anu#94]
`import { presetCore, presetThemeDefault } from 'anu-vue'`

**Comment by jd-solanki** [comment]
You need to import `presetAnu` instead of `presetCore` if you are using v0.11.0

**Comment by evanlong0926** [comment]
I use it according to README.md 'in the' anu-nuxt 'directory

**Comment by jd-solanki** [comment]
Oh, we need to update that.

Thanks for reporting. Are you using anu-nuxt?

**Comment by evanlong0926** [comment]
Yes, I'm using 'Nuxt3' and I'd like to use 'anu-nuxt' with it

**Comment by jd-solanki** [comment]
Did you managed to work it with `presetAnu`?

**Comment by evanlong0926** [comment]
I am going to try

**Comment by evanlong0926** [comment]
`
export default defineNuxtConfig({
  modules: ['@vueuse/nuxt', '@anu-vue/nuxt', '@unocss/nuxt', '@pinia/nuxt'],
  experimental: {
    reactivityTransform: false,
    inlineSSRStyles: false,
  },
  css: ['@unocss/reset/tailwind.css']
})
`

`
import { presetAnu, presetIconExtraProperties } from 'anu-vue'
import { presetThemeDefault } from '@anu-vue/preset-theme-default'

presetIcons({
    scale: 1.4,
    collections: {
        custom: {
          'left-bg': () => fs.readFile('./assets/left.svg', 'utf-8'),
          'right-bg': () => fs.readFile('./assets/right.svg', 'utf-8'),
        },
        carbon: () => import('@iconify-json/carbon/icons.json').then((i) => i.default as any),
      },
    extraProperties: presetIconExtraProperties,
 })
`

Unfortunately, after I used it, I couldn't display the style.😢

**Comment by jd-solanki** [comment]
You might be missing preset-theme-default styles:
```
import '@anu-vue/preset-theme-default/dist/styles.scss'
```

**Comment by jd-solanki** [comment]
Above is JS import, you have to adjust it according to nuxt. Maybe write in `css` option along with anu styles.

**Comment by evanlong0926** [comment]
> You might be missing preset-theme-default styles:
> 
> ```
> import '@anu-vue/preset-theme-default/dist/styles.scss'
> ```

```ts
export default defineNuxtConfig({
  modules: ['@vueuse/nuxt', '@anu-vue/nuxt', '@unocss/nuxt', '@pinia/nuxt'],
  experimental: {
    reactivityTransform: false,
    inlineSSRStyles: false,
  },
  css: ['@unocss/reset/tailwind.css', 'anu-vue/dist/style.css', '@anu-vue/preset-theme-default/dist/styles.scss']
})
```

And it turns out to be：
`[vite-node] [plugin:vite:css] [VITE_ERROR] /node_modules/.pnpm/@anu-vue+preset-theme-default@0.11.0/node_modules/@anu-vue/preset-theme-default/dist/styles.scss`

**Comment by jd-solanki** [comment]
Can you please share full screenshot?

**Comment by evanlong0926** [comment]
> Above is JS import, you have to adjust it according to nuxt. Maybe write in `css` option along with anu styles.

And I use `postcss` which cannot be introduced in `App.vue`

```vue
<style lang="postcss">
@import '@anu-vue/preset-theme-default/dist/styles.scss';

html,
body,
#__nuxt {
  @apply w-full h-100vh m-0 p-0  bg-dark-800 fixed z-5 text-white scrollbar;
}
/* * {
  cursor: url(https://api.iconify.design/carbon:3d-cursor.svg?height=16), default !important;
} */
</style>
```

**Comment by jd-solanki** [comment]
Why not use `lang="scss"`?

**Comment by evanlong0926** [comment]
> Why not use `lang="scss"`?

Because I'm not going to use the precompiler again after I use `Unocss`，I really like `Unocss` combined with `css`
`postcss` will focus more on compatibility, that's enough

**Comment by jd-solanki** [comment]
So, did you managed to make it work?

**Comment by evanlong0926** [comment]
> So, did you managed to make it work?

Not yet. I have to think about it😂

**Comment by jd-solanki** [comment]
Can you please share the full SS when you use 

```ts
css: ['@unocss/reset/tailwind.css', 'anu-vue/dist/style.css', '@anu-vue/preset-theme-default/dist/styles.scss']
```

**Comment by evanlong0926** [comment]
> Can you please share the full screenshot when you use
> 
> ```ts
> css: ['@unocss/reset/tailwind.css', 'anu-vue/dist/style.css', '@anu-vue/preset-theme-default/dist/styles.scss']
> ```

You mean an error message that the client is reporting?

**Comment by jd-solanki** [comment]
Yep. It should work according to me.

**Comment by evanlong0926** [comment]
> Can you please share the full screenshot when you use
> 
> ```ts
> css: ['@unocss/reset/tailwind.css', 'anu-vue/dist/style.css', '@anu-vue/preset-theme-default/dist/styles.scss']
> ```

![localhost_3000_admin_dashboard](https://user-images.githubusercontent.com/52912949/206988926-18c4f495-f195-4e72-a024-3a0067f315d8.png)

**Comment by jd-solanki** [comment]
We do provide css file for preset-theme-default in latest code changes however this isn't released yet.

Do you mind adding SCSS package for now? [installation guide](https://vitejs.dev/guide/features.html#css-pre-processors)

**Comment by evanlong0926** [comment]
> We do provide css file for preset-theme-default in latest code changes however this isn't released yet.
> 
> Do you mind adding SCSS package for now? [installation guide](https://vitejs.dev/guide/features.html#css-pre-processors)

No problem, I'll try

**Comment by evanlong0926** [comment]
> > We do provide css file for preset-theme-default in latest code changes however this isn't released yet.
> > Do you mind adding SCSS package for now? [installation guide](https://vitejs.dev/guide/features.html#css-pre-processors)
> 
> No problem, I'll try

I executed 'pnpm add -D sass sass-loader'.

This is the end result（The console reported no error）：
![微信截图_20221212155217](https://user-images.githubusercontent.com/52912949/206990940-12d3afd3-8df8-4706-af3c-f1ffdf2ea9ea.png)
![微信截图_20221212155223](https://user-images.githubusercontent.com/52912949/206990951-77b2478b-bdfd-40fa-ae23-4b85623681f3.png)

**Comment by evanlong0926** [comment]
> > > We do provide css file for preset-theme-default in latest code changes however this isn't released yet.
> > > Do you mind adding SCSS package for now? [installation guide](https://vitejs.dev/guide/features.html#css-pre-processors)
> > 
> > 
> > No problem, I'll try
> 
> I executed 'pnpm add -D sass sass-loader'.
> 
> This is the end result（The console reported no error）： ![微信截图_20221212155217](https://user-images.githubusercontent.com/52912949/206990940-12d3afd3-8df8-4706-af3c-f1ffdf2ea9ea.png) ![微信截图_20221212155223](https://user-images.githubusercontent.com/52912949/206990951-77b2478b-bdfd-40fa-ae23-4b85623681f3.png)

It seems like it only has color, but the core effect doesn't.

**Comment by jd-solanki** [comment]
let me check by creating new nuxt project. Will update the README today.

Thanks for reporting 👍🏻

**Comment by evanlong0926** [comment]
> let me check by creating new nuxt project. Will update the README today.
> 
> Thanks for reporting 👍🏻

I like your project very much, and I will help contribute in the future 😊

**Comment by jd-solanki** [comment]
![love-this-gif-by-late-night-with-seth-meyers](https://user-images.githubusercontent.com/47495003/206991979-2dd27d4e-e9fb-4ed5-a45c-79a739069e50.gif)

Love to have you 😇

**Comment by jd-solanki** [comment]
Hi,

You need to update the `include` option in `uno.config.ts` as below:
```ts
include: [/.*\/anu-vue\.js(.*)?$/, './**/*.vue', './**/*.md'],
```

I will update the package so it doesn't require this include in next release. I will update the docs as well.

**Comment by evanlong0926** [comment]
> Hi,
> 
> You need to update the `include` option in `uno.config.ts` as below:
> 
> ```ts
> include: [/.*\/anu-vue\.js(.*)?$/, './**/*.vue', './**/*.md'],
> ```
> 
> I will update the package so it doesn't require this include in next release. I will update the docs as well.

Ok

**Comment by evanlong0926** [comment]
> Hi,
> 
> You need to update the `include` option in `uno.config.ts` as below:
> 
> ```ts
> include: [/.*\/anu-vue\.js(.*)?$/, './**/*.vue', './**/*.md'],
> ```
> 
> I will update the package so it doesn't require this include in next release. I will update the docs as well.

With the effect of 👍：

![微信截图_20221213162202](https://user-images.githubusercontent.com/52912949/207263502-803638e9-099e-4fb0-b474-f60520324d40.png)
![微信截图_20221213162212](https://user-images.githubusercontent.com/52912949/207263510-9f156756-1c84-4e0a-8ed5-204eb78f50e9.png)

Expect the 'preset-theme-default' css file 😊.

**Comment by jd-solanki** [comment]
Awesome 🥳 

For handling light & dark you have to toggle the `.dark` class on `html` tag.

---

Have you ever created module in nuxt?

**Comment by evanlong0926** [comment]
> Awesome 🥳
> 
> For handling light & dark you have to toggle the `.dark` class on `html` tag.

Thanks for reminding me 😊

> 
> Have you ever created module in nuxt?

No, I only use Nuxt3 because I need SEO for my blog. More of my time would probably be spent creating aesthetically pleasing HTML elements, as I am interested in this 😉

**Comment by jd-solanki** [comment]
Let's keep this issue open for now. I will fix the nuxt module _(maybe I will need help)_ and afterward we will close this.

**Comment by evanlong0926** [comment]
> Let's keep this issue open for now. I will fix the nuxt module _(maybe I will need help)_ and afterward we will close this.
Ok.
>
maybe I will need help:
What can I do for you?🤔

**Comment by jd-solanki** [comment]
When we wrote the nuxt module we didn't have preset-theme-default as a separate package.

ATM we are just adding single CSS file in `packages/anu-nuxt/src/module.ts` however we also need include SCSS for preset-theme-default but when I add this line to `packages/anu-nuxt/playground/package.json` anu-nuxt's node_modules don't get `@anu-vue/preset-theme-default`.

🤔

**Comment by jd-solanki** [comment]
Hey, I think this issue is resolved now. I also update the docs that includes nuxt instructions: https://github.com/jd-solanki/anu/blob/main/docs/guide/getting-started/installation.md

However, docs will apply from next release, for now, you can continue with your setup.

Can we close this?

**Comment by evanlong0926** [comment]
> Hey, I think this issue is resolved now. I also update the docs that includes nuxt instructions: https://github.com/jd-solanki/anu/blob/main/docs/guide/getting-started/installation.md
> 
> However, docs will apply from next release, for now, you can continue with your setup.
> 
> Can we close this?

No problem, I'm sorry I didn't help you 🥲
