### ISSUE TITLE
Histoire.dev

### ISSUE THREAD

**Issue by ManUtopiK** [jd-solanki/anu#96]
Hi,

I've struggling with the colors and variants props, so I installed [histoire.dev](https://histoire.dev). Histoire is a pure vuejs alternative of storybook. It's a tool to build UI components in isolation.

You can try it with this branch : https://github.com/ManUtopiK/anu/tree/histoire and start with `nr clean && ni && nr build && nr story:dev`.
I started to build `ABtn` and especially `AList`, here are the screenshots:

![image](https://user-images.githubusercontent.com/188172/207662612-eafb62ca-87e8-4b9c-8572-d4ca679daff1.png)

![image](https://user-images.githubusercontent.com/188172/207662845-d1cdef72-bbf9-4705-af72-51bf1d47ac54.png)

What do you think about this?

**Comment by jd-solanki** [comment]
Hi,

I checked your clone. It's nice to have eagle eye over the components but I think maintaining docs & histoire both will be much more task.

What do you think of the burden it comes with?

**Comment by husayt** [comment]
Histoire might be a very good complement to docs. Yes, it comes at cost, but if there is a community support and volunteers ready to maintain it could be a great addition. This will address one of the existing shortcomings of the documentation. Anu allows for much more variety than what can be seen on the surface, histoire will help to expose that, show different variants, provide living examples.

**Comment by jd-solanki** [comment]
I haven't dug deeper into the histoire so I wanted to ask if can this be used as a playground so that if someone found a bug and he can report it with his link just like the [SFC playground](sfc.vuejs.org) or [UnoCSS playground](https://uno.antfu.me/play/).

**Comment by ManUtopiK** [comment]
> What do you think of the burden it comes with?

I started this just as an experiment and to help me to see all variants faster. I think it could be helpful for development, but HMR doesn't work well in my branch...
It surely could be benefit for developer to have Histoire as a complement to the docs. But yes, it's add more task. Sincerely, for now I think the new `anu UI` section with real case examples and tips is more relevant than adding Histoire.

> ... he can report it with his link just like the SFC playground...

We can't share a link like the playgrounds you mention (something like base64 url, or `btoa`).
As you can see in this [histoire.dev controls demo](https://controls.histoire.dev), the url changes depending on the story and variant ([example : primary variant of the HstButton story](https://controls.histoire.dev/story/histoire-controls-src-components-button-hstbutton-story-vue?variantId=histoire-controls-src-components-button-hstbutton-story-vue-1)), but not the controls.
But your idea is interesting. Maybe we can do that with a plugin or [controls slot](https://histoire.dev/examples/vue3/controlled-stories.html)...

**Comment by jd-solanki** [comment]
> I think the new anu UI section with real case examples and tips is more relevant than adding Histoire.

Awesome!

> We can't share a link like the playgrounds you mention

We can continue with histoire if it can provide a link like that so we can ask users for reproduction when they submit a bug. This is one of the tasks I want to definitely do at some point.

Thanks. Happy coding 🙌🏻

**Comment by jd-solanki** [comment]
Can we close this @ManUtopiK ?
