### ISSUE TITLE
use `@use` instead of `@import`

### ISSUE THREAD

**Issue by RebeccaStevens** [jd-solanki/anu#99]
https://github.com/jd-solanki/anu/blob/6a918dd2b3cd2574278d79348c266454210ec1b9/packages/preset-theme-default/src/scss/index.scss#L1

The `@import` isn't resolving properly for me. It seems to be trying to find a local file inside `preset-theme-default` instead of looking for `@unocss/reset` package.
`@use` fixes this issue for me.

**Comment by jd-solanki** [comment]
Closed via #105
